//! IndraDB on Twizzler — the RQ2 comparison baseline (board tasks D1/D2).
//!
//! **D1 (current):** no code of our own yet beyond smoke tests. The point is
//! to compile the *unmodified* upstream library for the Twizzler target and
//! exercise its in-memory datastore under the `--tests` harness, so the port
//! note is written from observed failures rather than guesses.
//!
//! Pinned surface (checked against docs.rs 2026-07-09, `indradb-lib` 5.0.0,
//! MPL-2.0):
//!
//! - `Database<D: Datastore>` is the user-facing type and holds the CRUD/query
//!   surface: `new`, `create_vertex`, `create_vertex_from_type`, `create_edge`,
//!   `get`, `delete`, `set_properties`, `bulk_insert`, `index_property`, `sync`.
//! - `Datastore` itself is **small** in 5.0 — one associated type and
//!   `fn transaction(&self) -> Self::Transaction<'_>`. The storage work lives
//!   in the `Transaction` trait, so D2's real target is `Transaction`, not the
//!   handful of methods the old (3.x/4.x) `Datastore` trait carried. Worth
//!   re-checking against the board's D2 wording before starting D2.
//! - `MemoryDatastore::new_db() -> Database<MemoryDatastore>` is the
//!   no-persistence constructor used below.
//!
//! Portability risks to watch on the first build (D1's actual output):
//! `tempfile` and `uuid` are non-optional dependencies; `MemoryDatastore`'s
//! msgpack persistence paths use `std::path`/filesystem APIs, and `uuid`'s v4
//! generation needs `getrandom` (the workspace already patches getrandom for
//! Twizzler, so that one may come free).

#[cfg(test)]
mod tests {
    use indradb::{
        Database, Edge, Identifier, MemoryDatastore, QueryExt, QueryOutputValue,
        SpecificVertexQuery,
    };

    /// Helper: the in-memory database used by every smoke test.
    fn db() -> Database<MemoryDatastore> {
        MemoryDatastore::new_db()
    }

    fn ident(s: &str) -> Identifier {
        Identifier::new(s).expect("valid identifier")
    }

    /// D1-AC2: create two vertices and one edge in the in-memory datastore,
    /// then read both back — vertices by id, and the edge by traversing
    /// outbound from its source.
    #[test]
    fn indradb_memory_vertices_and_edge_roundtrip() {
        let db = db();
        let person = ident("person");
        let knows = ident("knows");

        // Two vertices (ids generated by indradb).
        let a = db
            .create_vertex_from_type(person)
            .expect("create vertex a");
        let b = db
            .create_vertex_from_type(person)
            .expect("create vertex b");
        assert_ne!(a, b, "distinct vertex ids");

        // One edge a -> b.
        let edge = Edge::new(a, knows, b);
        assert!(db.create_edge(&edge).expect("create edge"), "edge created");

        // Query by id: vertex `a` comes back with the right type.
        let out = db.get(SpecificVertexQuery::single(a)).expect("get vertex a");
        match out.first().expect("one output value") {
            QueryOutputValue::Vertices(vs) => {
                assert_eq!(vs.len(), 1, "exactly one vertex");
                assert_eq!(vs[0].id, a);
                assert_eq!(vs[0].t, person);
            }
            other => panic!("expected Vertices, got {other:?}"),
        }

        // Edge query: outbound edges of `a` is exactly the a->b edge.
        let out = db
            .get(SpecificVertexQuery::single(a).outbound().expect("outbound"))
            .expect("get outbound edges");
        match out.last().expect("one output value") {
            QueryOutputValue::Edges(es) => {
                assert_eq!(es.len(), 1, "exactly one outbound edge");
                assert_eq!(es[0].outbound_id, a);
                assert_eq!(es[0].inbound_id, b);
                assert_eq!(es[0].t, knows);
            }
            other => panic!("expected Edges, got {other:?}"),
        }
    }

    /// A vertex that was never created is not returned — confirms queries
    /// actually consult the store rather than echoing the query.
    #[test]
    fn indradb_memory_missing_vertex_is_empty() {
        let db = db();
        let a = db
            .create_vertex_from_type(ident("thing"))
            .expect("create vertex");
        db.delete(SpecificVertexQuery::single(a)).expect("delete");

        let out = db.get(SpecificVertexQuery::single(a)).expect("get deleted");
        match out.first().expect("one output value") {
            QueryOutputValue::Vertices(vs) => assert!(vs.is_empty(), "deleted vertex gone"),
            other => panic!("expected Vertices, got {other:?}"),
        }
    }
}
